In [2]:
# NumPy is a linear algebra library for python
# NumPy arrays
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [4]:
import numpy as np
arr = np.array(my_list)

array([1, 2, 3, 4])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.16577652, 0.00651117, 0.79551687, 0.54910212, 0.59252762])

In [20]:
np.random.rand(5,5)

array([[0.11341335, 0.75647681, 0.79187033, 0.36031651, 0.3748519 ],
       [0.59932858, 0.67420946, 0.90029667, 0.07510974, 0.93092148],
       [0.68871633, 0.01165656, 0.18815973, 0.79919069, 0.58100077],
       [0.66051662, 0.38922788, 0.76680926, 0.62117002, 0.45119266],
       [0.76548101, 0.98897203, 0.99583768, 0.59725425, 0.80091212]])

In [21]:
np.random.randn(2)

array([-0.27562774,  1.07031775])

In [25]:
np.random.randint(1,100,100)

array([29, 61, 32, 15, 15, 64, 52, 16, 15, 70, 21,  9, 15, 60, 69, 66, 37,
       77, 62, 43, 47, 85, 83, 59,  2, 86, 62, 64, 33, 67, 71, 50, 38,  2,
       59, 59, 99, 65,  3,  7, 45, 91, 75, 71, 88, 45, 50,  3, 24,  8, 50,
       35, 10, 82, 62,  8, 47, 83, 91, 89, 61, 62, 18, 74, 57, 58, 86, 55,
       39, 32, 45, 26, 88, 59, 12,  6,  8, 79, 30, 54, 84, 16, 73, 82, 29,
       61, 17, 83, 76, 54, 84, 73, 63, 69, 41, 38, 76, 81, 71, 26])

In [34]:
arr = np.random.rand(10)
arr

array([0.16733056, 0.93644212, 0.4570886 , 0.31539497, 0.14940348,
       0.0408389 , 0.73067573, 0.84531796, 0.37618487, 0.12046985])

In [35]:
arr.reshape(2,5)

array([[0.16733056, 0.93644212, 0.4570886 , 0.31539497, 0.14940348],
       [0.0408389 , 0.73067573, 0.84531796, 0.37618487, 0.12046985]])

In [36]:
arr.max()

0.9364421234678697

In [37]:
arr.min()

0.04083890076042429

In [38]:
arr.argmax()

1

In [39]:
arr.argmin()

5

In [43]:
arr.shape

(10,)

In [44]:
arr.dtype

dtype('float64')

In [47]:
from numpy.random import randint

In [53]:
randint(1,20,10, dtype = int)

array([ 7,  9, 17,  7, 15,  6, 13, 15,  4, 13])

In [55]:
arrrr.dtype

dtype('int32')

# NumPy Indexing and Selection

In [57]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[8]

8

In [59]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [61]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
slice_of_arr = arr[0:6]
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [65]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr_copy = arr.copy()

In [68]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [69]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_2d = np.arange(16).reshape(4,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
arr_2d[2,3]

11

In [84]:
arr_2d[:2,2:]

array([[2, 3],
       [6, 7]])

In [90]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [93]:
bool_arr = arr > 5
bool_arr

array([False, False, False,  True,  True])

In [94]:
arr[bool_arr]

array([7, 9])

In [95]:
arr[arr>4]

array([5, 7, 9])

# NumPy Operations

In [103]:
arr = np.arange(0,11)

In [104]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [105]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [106]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [107]:
arr / arr

C:\Users\Imani\AppData\Local\Temp\ipykernel_13100\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [108]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [109]:
1/arr

C:\Users\Imani\AppData\Local\Temp\ipykernel_13100\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [110]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [111]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [112]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [113]:
np.max(arr)

10